FROM node:22-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN npm install -g turbo
RUN pnpm install

EXPOSE 3000

VOLUME [ "/app/node_modules", "/app/web/node_modules" ]

CMD ["pnpm", "dev", "--filter=web"]