services:
  web:
    container_name: plane-codecsrayo-web
    build:
      args:
        VITE_API_BASE_URL: https://plane.codecsrayo.com
        VITE_ADMIN_BASE_URL: https://plane.codecsrayo.com
        VITE_ADMIN_BASE_PATH: /god-mode
        VITE_LIVE_BASE_URL: https://plane.codecsrayo.com
        VITE_LIVE_BASE_PATH: /live
        VITE_SPACE_BASE_URL: https://plane.codecsrayo.com
        VITE_SPACE_BASE_PATH: /spaces
        VITE_WEB_BASE_URL: https://plane.codecsrayo.com

  admin:
    container_name: plane-codecsrayo-admin
    build:
      args:
        VITE_API_BASE_URL: https://plane.codecsrayo.com
        VITE_API_BASE_PATH: /api
        VITE_ADMIN_BASE_URL: https://plane.codecsrayo.com
        VITE_ADMIN_BASE_PATH: /god-mode
        VITE_SPACE_BASE_URL: https://plane.codecsrayo.com
        VITE_SPACE_BASE_PATH: /spaces
        VITE_LIVE_BASE_URL: https://plane.codecsrayo.com
        VITE_LIVE_BASE_PATH: /live
        VITE_WEB_BASE_URL: https://plane.codecsrayo.com
        VITE_WEB_BASE_PATH: ""

  space:
    container_name: plane-codecsrayo-space
    build:
      args:
        VITE_API_BASE_URL: https://plane.codecsrayo.com
        VITE_API_BASE_PATH: /api
        VITE_ADMIN_BASE_URL: https://plane.codecsrayo.com
        VITE_ADMIN_BASE_PATH: /god-mode
        VITE_SPACE_BASE_URL: https://plane.codecsrayo.com
        VITE_SPACE_BASE_PATH: /spaces
        VITE_LIVE_BASE_URL: https://plane.codecsrayo.com
        VITE_LIVE_BASE_PATH: /live
        VITE_WEB_BASE_URL: https://plane.codecsrayo.com
        VITE_WEB_BASE_PATH: ""

  api:
    container_name: plane-codecsrayo-api

  worker:
    container_name: plane-codecsrayo-worker

  beat-worker:
    container_name: plane-codecsrayo-beat-worker

  migrator:
    container_name: plane-codecsrayo-migrator

  live:
    container_name: plane-codecsrayo-live
    env_file:
      - ./apps/live/.env

  plane-db:
    container_name: plane-codecsrayo-db

  plane-redis:
    container_name: plane-codecsrayo-redis

  plane-mq:
    container_name: plane-codecsrayo-mq

  plane-minio:
    container_name: plane-codecsrayo-minio

  proxy:
    container_name: plane-codecsrayo-proxy
    ports: !reset []
    environment:
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
      SITE_ADDRESS: :80
      TRUSTED_PROXIES: 0.0.0.0/0
    networks:
      - default
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=proyectos-bi-quare
      - traefik.http.routers.plane-codecsrayo-http.rule=Host(`plane.codecsrayo.com`)
      - traefik.http.routers.plane-codecsrayo-http.entrypoints=web
      - traefik.http.routers.plane-codecsrayo-http.middlewares=plane-codecsrayo-https
      - traefik.http.middlewares.plane-codecsrayo-https.redirectscheme.scheme=https
      - traefik.http.routers.plane-codecsrayo.rule=Host(`plane.codecsrayo.com`)
      - traefik.http.routers.plane-codecsrayo.entrypoints=websecure
      - traefik.http.routers.plane-codecsrayo.tls=true
      - traefik.http.routers.plane-codecsrayo.tls.certresolver=netlify
      - traefik.http.services.plane-codecsrayo.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
    name: proyectos-bi-quare
