# Generated by Django 4.2.11

from django.db import migrations

def add_github_gitlab_integrations(apps, schema_editor):
    Integration = apps.get_model("db", "Integration")

    # Add GitHub
    Integration.objects.get_or_create(
        provider="github",
        defaults={
            "title": "GitHub",
            "network": 2, # Public
            "verified": True,
        }
    )

    # Add GitLab
    Integration.objects.get_or_create(
        provider="gitlab",
        defaults={
            "title": "GitLab",
            "network": 2, # Public
            "verified": True,
        }
    )

def remove_github_gitlab_integrations(apps, schema_editor):
    Integration = apps.get_model("db", "Integration")
    Integration.objects.filter(provider__in=["github", "gitlab"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.RunPython(add_github_gitlab_integrations, reverse_code=remove_github_gitlab_integrations),
    ]
