// src/entities/draft_issues.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "draft_issues")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub description_json: Json,
    #[sea_orm(column_type = "Text")]
    pub description_html: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_stripped: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub description_binary: Option<Vec<u8>>,
    pub priority: String,
    pub start_date: Option<Date>,
    pub target_date: Option<Date>,
    #[sea_orm(column_type = "Double")]
    pub sort_order: f64,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub external_source: Option<String>,
    pub external_id: Option<String>,
    pub created_by_id: Option<Uuid>,
    pub estimate_point_id: Option<Uuid>,
    pub parent_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    pub state_id: Option<Uuid>,
    pub type_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::draft_issue_assignees::Entity")]
    DraftIssueAssignees,
    #[sea_orm(has_many = "super::draft_issue_cycles::Entity")]
    DraftIssueCycles,
    #[sea_orm(has_many = "super::draft_issue_labels::Entity")]
    DraftIssueLabels,
    #[sea_orm(has_many = "super::draft_issue_modules::Entity")]
    DraftIssueModules,
    #[sea_orm(
        belongs_to = "super::estimate_points::Entity",
        from = "Column::EstimatePointId",
        to = "super::estimate_points::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EstimatePoints,
    #[sea_orm(has_many = "super::file_assets::Entity")]
    FileAssets,
    #[sea_orm(
        belongs_to = "super::issue_types::Entity",
        from = "Column::TypeId",
        to = "super::issue_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IssueTypes,
    #[sea_orm(
        belongs_to = "super::issues::Entity",
        from = "Column::ParentId",
        to = "super::issues::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Issues,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::draft_issue_assignees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueAssignees.def()
    }
}

impl Related<super::draft_issue_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueCycles.def()
    }
}

impl Related<super::draft_issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueLabels.def()
    }
}

impl Related<super::draft_issue_modules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueModules.def()
    }
}

impl Related<super::estimate_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EstimatePoints.def()
    }
}

impl Related<super::file_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAssets.def()
    }
}

impl Related<super::issue_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueTypes.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
