// src/entities/file_assets.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "file_assets")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub attributes: Json,
    pub asset: String,
    pub created_by_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Option<Uuid>,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub is_archived: bool,
    pub comment_id: Option<Uuid>,
    pub entity_type: Option<String>,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
    pub is_uploaded: bool,
    pub issue_id: Option<Uuid>,
    pub page_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    #[sea_orm(column_type = "Double")]
    pub size: f64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub storage_metadata: Option<Json>,
    pub user_id: Option<Uuid>,
    pub draft_issue_id: Option<Uuid>,
    pub entity_identifier: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::draft_issues::Entity",
        from = "Column::DraftIssueId",
        to = "super::draft_issues::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DraftIssues,
    #[sea_orm(
        belongs_to = "super::issue_comments::Entity",
        from = "Column::CommentId",
        to = "super::issue_comments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IssueComments,
    #[sea_orm(
        belongs_to = "super::issues::Entity",
        from = "Column::IssueId",
        to = "super::issues::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Issues,
    #[sea_orm(
        belongs_to = "super::pages::Entity",
        from = "Column::PageId",
        to = "super::pages::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pages,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::draft_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssues.def()
    }
}

impl Related<super::issue_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComments.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pages.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
