//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gitlab_repository_syncs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub credentials: Json,
    pub actor_id: Uuid,
    pub created_by_id: Option<Uuid>,
    pub label_id: Option<Uuid>,
    pub project_id: Uuid,
    #[sea_orm(unique)]
    pub repository_id: Uuid,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    pub workspace_integration_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gitlab_issue_syncs::Entity")]
    GitlabIssueSyncs,
    #[sea_orm(
        belongs_to = "super::gitlab_repositories::Entity",
        from = "Column::RepositoryId",
        to = "super::gitlab_repositories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GitlabRepositories,
    #[sea_orm(
        belongs_to = "super::labels::Entity",
        from = "Column::LabelId",
        to = "super::labels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Labels,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ActorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspace_integrations::Entity",
        from = "Column::WorkspaceIntegrationId",
        to = "super::workspace_integrations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkspaceIntegrations,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::gitlab_issue_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabIssueSyncs.def()
    }
}

impl Related<super::gitlab_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabRepositories.def()
    }
}

impl Related<super::labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Labels.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::workspace_integrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceIntegrations.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
