// src/entities/instances.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "instances")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub instance_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub whitelist_emails: Option<String>,
    #[sea_orm(unique)]
    pub instance_id: String,
    pub current_version: String,
    pub last_checked_at: DateTimeWithTimeZone,
    pub namespace: Option<String>,
    pub is_telemetry_enabled: bool,
    pub is_support_required: bool,
    pub is_setup_done: bool,
    pub is_signup_screen_visited: bool,
    pub is_verified: bool,
    pub created_by_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub domain: String,
    pub latest_version: Option<String>,
    pub edition: String,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub is_test: bool,
    pub is_current_version_deprecated: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::instance_admins::Entity")]
    InstanceAdmins,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::instance_admins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstanceAdmins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
