//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "integrations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    #[sea_orm(unique)]
    pub provider: String,
    pub network: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub description: Json,
    pub author: String,
    #[sea_orm(column_type = "Text")]
    pub webhook_url: String,
    #[sea_orm(column_type = "Text")]
    pub webhook_secret: String,
    #[sea_orm(column_type = "Text")]
    pub redirect_url: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    pub created_by_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(has_many = "super::workspace_integrations::Entity")]
    WorkspaceIntegrations,
}

impl Related<super::workspace_integrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceIntegrations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
