// src/entities/issues.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "issues")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub description_json: Json,
    pub priority: String,
    pub start_date: Option<Date>,
    pub target_date: Option<Date>,
    pub sequence_id: i32,
    pub created_by_id: Option<Uuid>,
    pub parent_id: Option<Uuid>,
    pub project_id: Uuid,
    pub state_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub description_html: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_stripped: Option<String>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double")]
    pub sort_order: f64,
    pub point: Option<i32>,
    pub archived_at: Option<Date>,
    pub is_draft: bool,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub description_binary: Option<Vec<u8>>,
    pub estimate_point_id: Option<Uuid>,
    pub type_id: Option<Uuid>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cycle_issues::Entity")]
    CycleIssues,
    #[sea_orm(has_many = "super::draft_issues::Entity")]
    DraftIssues,
    #[sea_orm(
        belongs_to = "super::estimate_points::Entity",
        from = "Column::EstimatePointId",
        to = "super::estimate_points::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EstimatePoints,
    #[sea_orm(has_many = "super::file_assets::Entity")]
    FileAssets,
    #[sea_orm(has_many = "super::github_issue_syncs::Entity")]
    GithubIssueSyncs,
    #[sea_orm(has_many = "super::gitlab_issue_syncs::Entity")]
    GitlabIssueSyncs,
    #[sea_orm(has_many = "super::issue_activities::Entity")]
    IssueActivities,
    #[sea_orm(has_many = "super::issue_assignees::Entity")]
    IssueAssignees,
    #[sea_orm(has_many = "super::issue_attachments::Entity")]
    IssueAttachments,
    #[sea_orm(has_many = "super::issue_comments::Entity")]
    IssueComments,
    #[sea_orm(has_many = "super::issue_description_versions::Entity")]
    IssueDescriptionVersions,
    #[sea_orm(has_many = "super::issue_labels::Entity")]
    IssueLabels,
    #[sea_orm(has_many = "super::issue_links::Entity")]
    IssueLinks,
    #[sea_orm(has_many = "super::issue_mentions::Entity")]
    IssueMentions,
    #[sea_orm(has_many = "super::issue_reactions::Entity")]
    IssueReactions,
    #[sea_orm(has_many = "super::issue_sequences::Entity")]
    IssueSequences,
    #[sea_orm(has_many = "super::issue_subscribers::Entity")]
    IssueSubscribers,
    #[sea_orm(
        belongs_to = "super::issue_types::Entity",
        from = "Column::TypeId",
        to = "super::issue_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IssueTypes,
    #[sea_orm(has_many = "super::issue_versions::Entity")]
    IssueVersions,
    #[sea_orm(has_many = "super::issue_votes::Entity")]
    IssueVotes,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::module_issues::Entity")]
    ModuleIssues,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::cycle_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CycleIssues.def()
    }
}

impl Related<super::draft_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssues.def()
    }
}

impl Related<super::estimate_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EstimatePoints.def()
    }
}

impl Related<super::file_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAssets.def()
    }
}

impl Related<super::github_issue_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubIssueSyncs.def()
    }
}

impl Related<super::gitlab_issue_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabIssueSyncs.def()
    }
}

impl Related<super::issue_activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueActivities.def()
    }
}

impl Related<super::issue_assignees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueAssignees.def()
    }
}

impl Related<super::issue_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueAttachments.def()
    }
}

impl Related<super::issue_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComments.def()
    }
}

impl Related<super::issue_description_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueDescriptionVersions.def()
    }
}

impl Related<super::issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabels.def()
    }
}

impl Related<super::issue_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLinks.def()
    }
}

impl Related<super::issue_mentions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueMentions.def()
    }
}

impl Related<super::issue_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueReactions.def()
    }
}

impl Related<super::issue_sequences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSequences.def()
    }
}

impl Related<super::issue_subscribers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSubscribers.def()
    }
}

impl Related<super::issue_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueTypes.def()
    }
}

impl Related<super::issue_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVersions.def()
    }
}

impl Related<super::issue_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVotes.def()
    }
}

impl Related<super::module_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleIssues.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
