// src/entities/labels.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "labels")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub created_by_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    pub parent_id: Option<Uuid>,
    pub color: String,
    #[sea_orm(column_type = "Double")]
    pub sort_order: f64,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::draft_issue_labels::Entity")]
    DraftIssueLabels,
    #[sea_orm(has_many = "super::github_repository_syncs::Entity")]
    GithubRepositorySyncs,
    #[sea_orm(has_many = "super::gitlab_repository_syncs::Entity")]
    GitlabRepositorySyncs,
    #[sea_orm(has_many = "super::issue_labels::Entity")]
    IssueLabels,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::page_labels::Entity")]
    PageLabels,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::draft_issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueLabels.def()
    }
}

impl Related<super::github_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositorySyncs.def()
    }
}

impl Related<super::gitlab_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabRepositorySyncs.def()
    }
}

impl Related<super::issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabels.def()
    }
}

impl Related<super::page_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageLabels.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
