// src/entities/modules.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "modules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_text: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_html: Option<Json>,
    pub start_date: Option<Date>,
    pub target_date: Option<Date>,
    pub status: String,
    pub created_by_id: Option<Uuid>,
    pub lead_id: Option<Uuid>,
    pub project_id: Uuid,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub view_props: Json,
    #[sea_orm(column_type = "Double")]
    pub sort_order: f64,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
    pub archived_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub logo_props: Json,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::draft_issue_modules::Entity")]
    DraftIssueModules,
    #[sea_orm(has_many = "super::module_issues::Entity")]
    ModuleIssues,
    #[sea_orm(has_many = "super::module_links::Entity")]
    ModuleLinks,
    #[sea_orm(has_many = "super::module_members::Entity")]
    ModuleMembers,
    #[sea_orm(has_many = "super::module_user_properties::Entity")]
    ModuleUserProperties,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::LeadId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::draft_issue_modules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueModules.def()
    }
}

impl Related<super::module_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleIssues.def()
    }
}

impl Related<super::module_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleLinks.def()
    }
}

impl Related<super::module_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleMembers.def()
    }
}

impl Related<super::module_user_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleUserProperties.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
