//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "pages")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub description_json: Json,
    #[sea_orm(column_type = "Text")]
    pub description_html: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_stripped: Option<String>,
    pub access: i16,
    pub created_by_id: Option<Uuid>,
    pub owned_by_id: Uuid,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    pub color: String,
    pub archived_at: Option<Date>,
    pub is_locked: bool,
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub view_props: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub logo_props: Json,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub description_binary: Option<Vec<u8>>,
    pub is_global: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub moved_to_page: Option<Uuid>,
    pub moved_to_project: Option<Uuid>,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub sort_order: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_assets::Entity")]
    FileAssets,
    #[sea_orm(has_many = "super::page_labels::Entity")]
    PageLabels,
    #[sea_orm(has_many = "super::page_logs::Entity")]
    PageLogs,
    #[sea_orm(has_many = "super::page_versions::Entity")]
    PageVersions,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::project_pages::Entity")]
    ProjectPages,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::file_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAssets.def()
    }
}

impl Related<super::page_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageLabels.def()
    }
}

impl Related<super::page_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageLogs.def()
    }
}

impl Related<super::page_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageVersions.def()
    }
}

impl Related<super::project_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPages.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
