//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub theme: Json,
    pub is_tour_completed: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub onboarding_step: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub use_case: Option<String>,
    pub role: Option<String>,
    pub is_onboarded: bool,
    pub last_workspace_id: Option<Uuid>,
    pub billing_address_country: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub billing_address: Option<Json>,
    pub has_billing_address: bool,
    pub company_name: String,
    #[sea_orm(unique)]
    pub user_id: Uuid,
    pub is_mobile_onboarded: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub mobile_onboarding_step: Json,
    pub mobile_timezone_auto_set: bool,
    pub language: String,
    pub is_smooth_cursor_enabled: bool,
    pub start_of_the_week: i16,
    pub is_app_rail_docked: bool,
    pub background_color: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub goals: Json,
    pub has_marketing_email_consent: bool,
    pub is_navigation_tour_completed: bool,
    pub is_subscribed_to_changelog: bool,
    pub notification_view_mode: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub product_tour: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
