// src/entities/projects.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_text: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_html: Option<Json>,
    pub network: i16,
    pub identifier: String,
    pub created_by_id: Option<Uuid>,
    pub default_assignee_id: Option<Uuid>,
    pub project_lead_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    pub emoji: Option<String>,
    pub cycle_view: bool,
    pub module_view: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    pub issue_views_view: bool,
    pub page_view: bool,
    pub estimate_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub icon_prop: Option<Json>,
    pub intake_view: bool,
    pub archive_in: i32,
    pub close_in: i32,
    pub default_state_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub logo_props: Json,
    pub archived_at: Option<DateTimeWithTimeZone>,
    pub is_time_tracking_enabled: bool,
    pub is_issue_type_enabled: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub guest_view_all_features: bool,
    pub timezone: String,
    pub cover_image_asset_id: Option<Uuid>,
    pub external_id: Option<String>,
    pub external_source: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comment_reactions::Entity")]
    CommentReactions,
    #[sea_orm(has_many = "super::cycle_issues::Entity")]
    CycleIssues,
    #[sea_orm(has_many = "super::cycle_user_properties::Entity")]
    CycleUserProperties,
    #[sea_orm(has_many = "super::cycles::Entity")]
    Cycles,
    #[sea_orm(has_many = "super::db_githubprstatemapping::Entity")]
    DbGithubprstatemapping,
    #[sea_orm(has_many = "super::deploy_boards::Entity")]
    DeployBoards,
    #[sea_orm(has_many = "super::description_versions::Entity")]
    DescriptionVersions,
    #[sea_orm(has_many = "super::descriptions::Entity")]
    Descriptions,
    #[sea_orm(has_many = "super::draft_issue_assignees::Entity")]
    DraftIssueAssignees,
    #[sea_orm(has_many = "super::draft_issue_cycles::Entity")]
    DraftIssueCycles,
    #[sea_orm(has_many = "super::draft_issue_labels::Entity")]
    DraftIssueLabels,
    #[sea_orm(has_many = "super::draft_issue_modules::Entity")]
    DraftIssueModules,
    #[sea_orm(has_many = "super::draft_issues::Entity")]
    DraftIssues,
    #[sea_orm(has_many = "super::estimate_points::Entity")]
    EstimatePoints,
    #[sea_orm(
        belongs_to = "super::estimates::Entity",
        from = "Column::EstimateId",
        to = "super::estimates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Estimates,
    #[sea_orm(
        belongs_to = "super::file_assets::Entity",
        from = "Column::CoverImageAssetId",
        to = "super::file_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileAssets,
    #[sea_orm(has_many = "super::github_comment_syncs::Entity")]
    GithubCommentSyncs,
    #[sea_orm(has_many = "super::github_issue_syncs::Entity")]
    GithubIssueSyncs,
    #[sea_orm(has_many = "super::github_repositories::Entity")]
    GithubRepositories,
    #[sea_orm(has_many = "super::github_repository_syncs::Entity")]
    GithubRepositorySyncs,
    #[sea_orm(has_many = "super::gitlab_comment_syncs::Entity")]
    GitlabCommentSyncs,
    #[sea_orm(has_many = "super::gitlab_issue_syncs::Entity")]
    GitlabIssueSyncs,
    #[sea_orm(has_many = "super::gitlab_repositories::Entity")]
    GitlabRepositories,
    #[sea_orm(has_many = "super::gitlab_repository_syncs::Entity")]
    GitlabRepositorySyncs,
    #[sea_orm(has_many = "super::importers::Entity")]
    Importers,
    #[sea_orm(has_many = "super::intake_issues::Entity")]
    IntakeIssues,
    #[sea_orm(has_many = "super::intakes::Entity")]
    Intakes,
    #[sea_orm(has_many = "super::issue_activities::Entity")]
    IssueActivities,
    #[sea_orm(has_many = "super::issue_assignees::Entity")]
    IssueAssignees,
    #[sea_orm(has_many = "super::issue_attachments::Entity")]
    IssueAttachments,
    #[sea_orm(has_many = "super::issue_blockers::Entity")]
    IssueBlockers,
    #[sea_orm(has_many = "super::issue_comments::Entity")]
    IssueComments,
    #[sea_orm(has_many = "super::issue_description_versions::Entity")]
    IssueDescriptionVersions,
    #[sea_orm(has_many = "super::issue_labels::Entity")]
    IssueLabels,
    #[sea_orm(has_many = "super::issue_links::Entity")]
    IssueLinks,
    #[sea_orm(has_many = "super::issue_mentions::Entity")]
    IssueMentions,
    #[sea_orm(has_many = "super::issue_reactions::Entity")]
    IssueReactions,
    #[sea_orm(has_many = "super::issue_relations::Entity")]
    IssueRelations,
    #[sea_orm(has_many = "super::issue_sequences::Entity")]
    IssueSequences,
    #[sea_orm(has_many = "super::issue_subscribers::Entity")]
    IssueSubscribers,
    #[sea_orm(has_many = "super::issue_versions::Entity")]
    IssueVersions,
    #[sea_orm(has_many = "super::issue_views::Entity")]
    IssueViews,
    #[sea_orm(has_many = "super::issue_votes::Entity")]
    IssueVotes,
    #[sea_orm(has_many = "super::issues::Entity")]
    Issues,
    #[sea_orm(has_many = "super::labels::Entity")]
    Labels,
    #[sea_orm(has_many = "super::module_issues::Entity")]
    ModuleIssues,
    #[sea_orm(has_many = "super::module_links::Entity")]
    ModuleLinks,
    #[sea_orm(has_many = "super::module_members::Entity")]
    ModuleMembers,
    #[sea_orm(has_many = "super::module_user_properties::Entity")]
    ModuleUserProperties,
    #[sea_orm(has_many = "super::modules::Entity")]
    Modules,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::project_deploy_boards::Entity")]
    ProjectDeployBoards,
    #[sea_orm(has_one = "super::project_identifiers::Entity")]
    ProjectIdentifiers,
    #[sea_orm(has_many = "super::project_issue_types::Entity")]
    ProjectIssueTypes,
    #[sea_orm(has_many = "super::project_member_invites::Entity")]
    ProjectMemberInvites,
    #[sea_orm(has_many = "super::project_members::Entity")]
    ProjectMembers,
    #[sea_orm(has_many = "super::project_pages::Entity")]
    ProjectPages,
    #[sea_orm(has_many = "super::project_public_members::Entity")]
    ProjectPublicMembers,
    #[sea_orm(has_many = "super::project_user_properties::Entity")]
    ProjectUserProperties,
    #[sea_orm(has_many = "super::project_webhooks::Entity")]
    ProjectWebhooks,
    #[sea_orm(has_many = "super::slack_project_syncs::Entity")]
    SlackProjectSyncs,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::DefaultStateId",
        to = "super::states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
    #[sea_orm(has_many = "super::user_favorites::Entity")]
    UserFavorites,
    #[sea_orm(has_many = "super::user_notification_preferences::Entity")]
    UserNotificationPreferences,
    #[sea_orm(has_many = "super::user_recent_visits::Entity")]
    UserRecentVisits,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users4,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::DefaultAssigneeId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ProjectLeadId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(has_many = "super::workspace_user_links::Entity")]
    WorkspaceUserLinks,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::comment_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentReactions.def()
    }
}

impl Related<super::cycle_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CycleIssues.def()
    }
}

impl Related<super::cycle_user_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CycleUserProperties.def()
    }
}

impl Related<super::cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cycles.def()
    }
}

impl Related<super::db_githubprstatemapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbGithubprstatemapping.def()
    }
}

impl Related<super::deploy_boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeployBoards.def()
    }
}

impl Related<super::description_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DescriptionVersions.def()
    }
}

impl Related<super::descriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Descriptions.def()
    }
}

impl Related<super::draft_issue_assignees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueAssignees.def()
    }
}

impl Related<super::draft_issue_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueCycles.def()
    }
}

impl Related<super::draft_issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueLabels.def()
    }
}

impl Related<super::draft_issue_modules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssueModules.def()
    }
}

impl Related<super::draft_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DraftIssues.def()
    }
}

impl Related<super::estimate_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EstimatePoints.def()
    }
}

impl Related<super::estimates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Estimates.def()
    }
}

impl Related<super::file_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAssets.def()
    }
}

impl Related<super::github_comment_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubCommentSyncs.def()
    }
}

impl Related<super::github_issue_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubIssueSyncs.def()
    }
}

impl Related<super::github_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositories.def()
    }
}

impl Related<super::github_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositorySyncs.def()
    }
}

impl Related<super::gitlab_comment_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabCommentSyncs.def()
    }
}

impl Related<super::gitlab_issue_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabIssueSyncs.def()
    }
}

impl Related<super::gitlab_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabRepositories.def()
    }
}

impl Related<super::gitlab_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabRepositorySyncs.def()
    }
}

impl Related<super::importers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Importers.def()
    }
}

impl Related<super::intake_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntakeIssues.def()
    }
}

impl Related<super::intakes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Intakes.def()
    }
}

impl Related<super::issue_activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueActivities.def()
    }
}

impl Related<super::issue_assignees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueAssignees.def()
    }
}

impl Related<super::issue_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueAttachments.def()
    }
}

impl Related<super::issue_blockers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueBlockers.def()
    }
}

impl Related<super::issue_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComments.def()
    }
}

impl Related<super::issue_description_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueDescriptionVersions.def()
    }
}

impl Related<super::issue_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabels.def()
    }
}

impl Related<super::issue_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLinks.def()
    }
}

impl Related<super::issue_mentions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueMentions.def()
    }
}

impl Related<super::issue_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueReactions.def()
    }
}

impl Related<super::issue_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueRelations.def()
    }
}

impl Related<super::issue_sequences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSequences.def()
    }
}

impl Related<super::issue_subscribers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSubscribers.def()
    }
}

impl Related<super::issue_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVersions.def()
    }
}

impl Related<super::issue_views::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueViews.def()
    }
}

impl Related<super::issue_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVotes.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Labels.def()
    }
}

impl Related<super::module_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleIssues.def()
    }
}

impl Related<super::module_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleLinks.def()
    }
}

impl Related<super::module_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleMembers.def()
    }
}

impl Related<super::module_user_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModuleUserProperties.def()
    }
}

impl Related<super::modules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Modules.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::project_deploy_boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectDeployBoards.def()
    }
}

impl Related<super::project_identifiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectIdentifiers.def()
    }
}

impl Related<super::project_issue_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectIssueTypes.def()
    }
}

impl Related<super::project_member_invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMemberInvites.def()
    }
}

impl Related<super::project_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembers.def()
    }
}

impl Related<super::project_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPages.def()
    }
}

impl Related<super::project_public_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPublicMembers.def()
    }
}

impl Related<super::project_user_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectUserProperties.def()
    }
}

impl Related<super::project_webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectWebhooks.def()
    }
}

impl Related<super::slack_project_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SlackProjectSyncs.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::user_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFavorites.def()
    }
}

impl Related<super::user_notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNotificationPreferences.def()
    }
}

impl Related<super::user_recent_visits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRecentVisits.def()
    }
}

impl Related<super::workspace_user_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceUserLinks.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
