// src/entities/sessions.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub session_data: String,
    pub expire_date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub device_info: Option<Json>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub session_key: String,
    pub user_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_sessions::Entity")]
    DeviceSessions,
}

impl Related<super::device_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
