//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub password: String,
    pub last_login: Option<DateTimeWithTimeZone>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub mobile_number: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(column_type = "Text")]
    pub avatar: String,
    pub date_joined: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_location: String,
    pub created_location: String,
    pub is_superuser: bool,
    pub is_managed: bool,
    pub is_password_expired: bool,
    pub is_active: bool,
    pub is_staff: bool,
    pub is_email_verified: bool,
    pub is_password_autoset: bool,
    pub token: String,
    pub user_timezone: String,
    pub last_active: Option<DateTimeWithTimeZone>,
    pub last_login_time: Option<DateTimeWithTimeZone>,
    pub last_logout_time: Option<DateTimeWithTimeZone>,
    pub last_login_ip: String,
    pub last_logout_ip: String,
    pub last_login_medium: String,
    #[sea_orm(column_type = "Text")]
    pub last_login_uagent: String,
    pub token_updated_at: Option<DateTimeWithTimeZone>,
    pub is_bot: bool,
    pub cover_image: Option<String>,
    pub display_name: String,
    pub avatar_asset_id: Option<Uuid>,
    pub cover_image_asset_id: Option<Uuid>,
    pub bot_type: Option<String>,
    pub is_email_valid: bool,
    pub masked_at: Option<DateTimeWithTimeZone>,
    pub is_password_reset_required: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
    #[sea_orm(
        belongs_to = "super::file_assets::Entity",
        from = "Column::AvatarAssetId",
        to = "super::file_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileAssets2,
    #[sea_orm(
        belongs_to = "super::file_assets::Entity",
        from = "Column::CoverImageAssetId",
        to = "super::file_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileAssets1,
    #[sea_orm(has_one = "super::profiles::Entity")]
    Profiles,
    #[sea_orm(has_many = "super::users_groups::Entity")]
    UsersGroups,
    #[sea_orm(has_many = "super::users_user_permissions::Entity")]
    UsersUserPermissions,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl Related<super::users_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersGroups.def()
    }
}

impl Related<super::users_user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersUserPermissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
