// src/entities/webhook_logs.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webhook_logs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_type: Option<String>,
    pub request_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_headers: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_headers: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_body: Option<String>,
    pub retry_count: i16,
    pub created_by_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    pub webhook: Uuid,
    pub workspace_id: Uuid,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
