// src/entities/workspace_integrations.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workspace_integrations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    pub actor_id: Uuid,
    pub api_token_id: Uuid,
    pub created_by_id: Option<Uuid>,
    pub integration_id: Uuid,
    pub updated_by_id: Option<Uuid>,
    pub workspace_id: Uuid,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::api_tokens::Entity",
        from = "Column::ApiTokenId",
        to = "super::api_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ApiTokens,
    #[sea_orm(has_many = "super::db_githubprstatemapping::Entity")]
    DbGithubprstatemapping,
    #[sea_orm(has_many = "super::github_repository_syncs::Entity")]
    GithubRepositorySyncs,
    #[sea_orm(has_many = "super::gitlab_repository_syncs::Entity")]
    GitlabRepositorySyncs,
    #[sea_orm(
        belongs_to = "super::integrations::Entity",
        from = "Column::IntegrationId",
        to = "super::integrations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Integrations,
    #[sea_orm(has_many = "super::slack_project_syncs::Entity")]
    SlackProjectSyncs,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ActorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::api_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiTokens.def()
    }
}

impl Related<super::db_githubprstatemapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbGithubprstatemapping.def()
    }
}

impl Related<super::github_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositorySyncs.def()
    }
}

impl Related<super::gitlab_repository_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitlabRepositorySyncs.def()
    }
}

impl Related<super::integrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Integrations.def()
    }
}

impl Related<super::slack_project_syncs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SlackProjectSyncs.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
