// src/utils/content_validator.rs
//! Content validation and sanitization for Pages.
//!
//! Mirrors `apps/api/plane/utils/content_validator.py` — includes:
//! * `validate_binary_data`: maximum size (10 MB), minimum length and detection
//!   of suspicious HTML/JS patterns (attack markers embedded in what
//!   should be a binary Y.js document).
//! * `validate_html_content`: maximum size and sanitization with `ammonia`,
//!   preserving Plane editor custom tags and attributes
//!   (`mention-component`, `image-component`, `input`, etc.) so as not to lose
//!   data when saving HTML generated by the collaborative editor.
//!
//! The lists of tags, attributes and protocols exactly replicate those
//! defined in Python to guarantee bidirectional compatibility when the
//! Rust backend runs in parallel with Django.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

/// Maximum size allowed for content (binary or HTML): 10 MB.
/// Mirror of `MAX_SIZE` in `content_validator.py`.
pub const MAX_CONTENT_SIZE: usize = 10 * 1024 * 1024;

/// Reasonable minimum length for a binary Y.js document — shorter values
/// are suspicious (a legitimate empty doc already occupies >=4 bytes of header).
const MIN_BINARY_LEN: usize = 4;

/// Patterns that should not appear in a binary Y.js — their presence suggests
/// that someone is trying to pass disguised HTML/JS.
const SUSPICIOUS_BINARY_PATTERNS: &[&str] = &[
    "<html",
    "<!doctype",
    "<script",
    "javascript:",
    "data:",
    "<iframe",
];

/// Plane editor custom tags (in addition to ammonia defaults).
/// Must match `CUSTOM_TAGS` in Python.
const CUSTOM_TAGS: &[&str] = &["mention-component", "label", "input", "image-component"];

/// "Generic" attributes allowed on any tag.
/// Mirror of `ATTRIBUTES["*"]` in Python.
const GENERIC_ATTRS: &[&str] = &[
    "class",
    "id",
    "title",
    "role",
    "aria-label",
    "aria-hidden",
    "style",
    "start",
    "type",
    "xmlns",
    // data-* conocidos del editor
    "data-tight",
    "data-node-type",
    "data-type",
    "data-checked",
    "data-background-color",
    "data-text-color",
    "data-name",
    "data-id",
    // callouts
    "data-icon-name",
    "data-icon-color",
    "data-background",
    "data-emoji-unicode",
    "data-emoji-url",
    "data-logo-in-use",
    "data-block-type",
];

/// Protocols allowed in URLs.
/// Mirror of `SAFE_PROTOCOLS` in Python.
const SAFE_PROTOCOLS: &[&str] = &["http", "https", "mailto", "tel"];

/// Allowed attribute prefixes (generic) — equivalent to the dynamic
/// handling of `data-*` in Python, which inspects the input HTML.
/// With `ammonia` we use `generic_attribute_prefixes` to accept any
/// `data-*` without having to list them one by one.
const GENERIC_ATTR_PREFIXES: &[&str] = &["data-"];

/// Builds (only once) the reusable `ammonia::Builder` with all the
/// editor configuration. Caching is cheap and avoids rebuilding the
/// structure for each request — which repeats with high frequency when the
/// collaborative client persists HTML on every keystroke.
fn builder() -> &'static ammonia::Builder<'static> {
    static BUILDER: OnceLock<ammonia::Builder<'static>> = OnceLock::new();
    BUILDER.get_or_init(|| {
        let mut b = ammonia::Builder::default();

        // Tags: defaults + custom from editor
        b.add_tags(CUSTOM_TAGS.iter().copied());

        // Generic attributes (apply to "*")
        b.add_generic_attributes(GENERIC_ATTRS.iter().copied());

        // dynamic data-* without enumerating
        b.add_generic_attribute_prefixes(GENERIC_ATTR_PREFIXES.iter().copied());

        // Specific attributes per tag — mirror of `ATTRIBUTES` by key
        let mut per_tag: HashMap<&'static str, HashSet<&'static str>> = HashMap::new();
        per_tag.insert("a", ["href", "target"].into_iter().collect());
        per_tag.insert(
            "image-component",
            [
                "id",
                "width",
                "height",
                "aspectRatio",
                "aspectratio",
                "src",
                "alignment",
                "status",
            ]
            .into_iter()
            .collect(),
        );
        per_tag.insert(
            "img",
            [
                "width",
                "height",
                "aspectRatio",
                "aspectratio",
                "alignment",
                "src",
                "alt",
                "title",
            ]
            .into_iter()
            .collect(),
        );
        per_tag.insert(
            "mention-component",
            ["id", "entity_identifier", "entity_name"].into_iter().collect(),
        );
        per_tag.insert(
            "th",
            ["colspan", "rowspan", "colwidth", "background", "style"]
                .into_iter()
                .collect(),
        );
        per_tag.insert(
            "td",
            [
                "colspan",
                "rowspan",
                "colwidth",
                "background",
                "textColor",
                "textcolor",
                "style",
            ]
            .into_iter()
            .collect(),
        );
        per_tag.insert(
            "tr",
            ["background", "textColor", "textcolor", "style"]
                .into_iter()
                .collect(),
        );
        per_tag.insert("pre", ["language"].into_iter().collect());
        per_tag.insert("code", ["language", "spellcheck"].into_iter().collect());
        per_tag.insert("input", ["type", "checked"].into_iter().collect());
        for (tag, attrs) in per_tag {
            b.add_tag_attributes(tag, attrs);
        }

        // Allowed URL schemes
        b.url_schemes(SAFE_PROTOCOLS.iter().copied().collect());

        b
    })
}

/// Validates a binary blob (Y.js document) before persisting it.
///
/// Returns `Ok(())` if it passes, `Err(msg)` if any rule fails. An empty buffer
/// is considered valid (Django accepts it as "no content yet").
pub fn validate_binary_data(data: &[u8]) -> Result<(), String> {
    if data.is_empty() {
        return Ok(());
    }
    if data.len() > MAX_CONTENT_SIZE {
        return Err("Binary data exceeds maximum size limit (10MB)".to_string());
    }
    if data.len() < MIN_BINARY_LEN {
        return Err("Binary data too short to be valid document format".to_string());
    }

    // Check for suspicious patterns in the first 200 bytes treated as
    // best-effort UTF-8 (invalid bytes are replaced by U+FFFD).
    let prefix_len = data.len().min(200);
    let sniff = String::from_utf8_lossy(&data[..prefix_len]).to_lowercase();
    for pattern in SUSPICIOUS_BINARY_PATTERNS {
        if sniff.contains(pattern) {
            return Err("Binary data contains suspicious content patterns".to_string());
        }
    }

    Ok(())
}

/// Validates and sanitizes HTML. Returns the clean HTML or a descriptive error.
///
/// * Empty HTML → `Ok(String::new())` without calling the sanitizer.
/// * Size > 10 MB → rejects.
/// * General case → `ammonia::clean` with the editor config.
pub fn sanitize_description(html: &str) -> Result<String, String> {
    if html.is_empty() {
        return Ok(String::new());
    }
    if html.len() > MAX_CONTENT_SIZE {
        return Err("HTML content exceeds maximum size limit (10MB)".to_string());
    }
    Ok(builder().clean(html).to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_binary_is_valid() {
        assert!(validate_binary_data(&[]).is_ok());
    }

    #[test]
    fn tiny_binary_rejected() {
        assert!(validate_binary_data(&[1, 2]).is_err());
    }

    #[test]
    fn oversized_binary_rejected() {
        let big = vec![0u8; MAX_CONTENT_SIZE + 1];
        assert!(validate_binary_data(&big).is_err());
    }

    #[test]
    fn suspicious_binary_rejected() {
        let payload = b"<!DOCTYPE html><html><script>alert(1)</script>".to_vec();
        assert!(validate_binary_data(&payload).is_err());
    }

    #[test]
    fn normal_binary_accepted() {
        // 4+ bytes, no HTML patterns
        let payload = vec![0x00, 0x01, 0x02, 0x03, 0x04, 0x05];
        assert!(validate_binary_data(&payload).is_ok());
    }

    #[test]
    fn empty_html_returns_empty() {
        assert_eq!(sanitize_description("").unwrap(), "");
    }

    #[test]
    fn html_over_limit_rejected() {
        let big = "a".repeat(MAX_CONTENT_SIZE + 1);
        assert!(sanitize_description(&big).is_err());
    }

    #[test]
    fn script_tag_stripped() {
        let dirty = "<p>hi</p><script>evil()</script>";
        let clean = sanitize_description(dirty).unwrap();
        assert!(!clean.contains("<script"));
        assert!(clean.contains("<p>hi</p>"));
    }

    #[test]
    fn mention_component_preserved() {
        let dirty = r#"<p>hola <mention-component id="u1" entity_identifier="user-id" entity_name="user_mention"></mention-component></p>"#;
        let clean = sanitize_description(dirty).unwrap();
        assert!(
            clean.contains("<mention-component"),
            "mention-component must be preserved, got: {clean}"
        );
        assert!(clean.contains("entity_identifier"));
    }

    #[test]
    fn data_attributes_preserved() {
        let dirty = r#"<div data-block-type="callout" data-icon-name="sparkles">x</div>"#;
        let clean = sanitize_description(dirty).unwrap();
        assert!(clean.contains("data-block-type"));
        assert!(clean.contains("data-icon-name"));
    }

    #[test]
    fn javascript_url_stripped() {
        let dirty = r#"<a href="javascript:alert(1)">x</a>"#;
        let clean = sanitize_description(dirty).unwrap();
        assert!(!clean.contains("javascript:"));
    }
}
