// src/utils/token_cipher.rs
//
//! Symmetric encryption of OAuth tokens at rest.
//!
//! ## Algorithm
//! AES-256-GCM with a random 96-bit (12-byte) nonce generated by the OS.
//! The 128-bit (16-byte) auth tag is included in the ciphertext returned
//! by `aes_gcm::Aead::encrypt`.
//!
//! ## Database Format
//! ```text
//! v1:<base64-standard(nonce[12] || ciphertext_with_tag)>
//! ```
//!
//! The `v1:` prefix allows for schema version detection and distinguishing encrypted
//! rows from legacy plaintext rows from the Django API.
//!
//! ## Backward Compatibility
//! `decrypt_token` accepts values without the `v1:` prefix and returns them as is.
//! This allows for gradual migration: Django rows remain readable until
//! they are re-encrypted in a coordinated migration job.
//!
//! ## Configuration
//! Environment variable: `TOKEN_ENCRYPTION_KEY`
//! Value: 32-byte key encoded in base64-standard.
//!
//! Example key generation:
//! ```bash
//! openssl rand -base64 32
//! ```
//!
//! ## Degradation when the key is not configured
//! - **Writing**: a `WARN` is logged and stored in plain text.
//!   Allows deployments without breaking functionality, but the warning is visible
//!   in production logs to demand configuration.
//! - **Reading**: token without `v1:` prefix → direct return (legacy plaintext).
//!   Token with `v1:` prefix without key → `AppError::Internal` (inconsistency).

use aes_gcm::{
    aead::{Aead, AeadCore, KeyInit, OsRng},
    Aes256Gcm, Nonce,
};
use base64::{engine::general_purpose::STANDARD, Engine as _};

use crate::error::AppError;

/// Version prefix. Allows distinguishing encrypted tokens from legacy plaintext.
const TOKEN_PREFIX: &str = "v1:";

/// Environment variable with the AES-256-GCM key (base64, 32 bytes).
const KEY_ENV_VAR: &str = "TOKEN_ENCRYPTION_KEY";

/// Loads the 32-byte key from `TOKEN_ENCRYPTION_KEY`.
///
/// Returns `None` if the variable doesn't exist, isn't valid base64, or doesn't have 32 bytes.
fn load_key() -> Option<[u8; 32]> {
    let b64 = std::env::var(KEY_ENV_VAR).ok()?;
    let bytes = STANDARD.decode(b64.trim()).ok()?;
    if bytes.len() != 32 {
        tracing::error!(
            var = KEY_ENV_VAR,
            actual_bytes = bytes.len(),
            expected_bytes = 32,
            "TOKEN_ENCRYPTION_KEY has incorrect length — it will be ignored"
        );
        return None;
    }
    let mut key = [0u8; 32];
    key.copy_from_slice(&bytes);
    Some(key)
}

/// Encrypts an OAuth token with AES-256-GCM and returns `v1:<b64(nonce||ciphertext)>`.
///
/// If `TOKEN_ENCRYPTION_KEY` is not configured, returns the original value
/// with a `WARN` in logs — soft degradation that doesn't break existing deployments.
///
/// # Panics
/// Does not panic: `Aes256Gcm::new_from_slice` only fails if the key
/// doesn't have 32 bytes, a condition verified in `load_key`.
pub fn encrypt_token(plaintext: &str) -> String {
    let Some(key_bytes) = load_key() else {
        tracing::warn!(
            var = KEY_ENV_VAR,
            "TOKEN_ENCRYPTION_KEY not configured — GitHub access_token stored in \
             plain text. Configure the variable to enable AES-256-GCM at rest."
        );
        return plaintext.to_owned();
    };

    // new_from_slice doesn't fail: load_key guarantees exactly 32 bytes.
    let cipher = Aes256Gcm::new_from_slice(&key_bytes)
        .expect("load_key guarantees 32 bytes — new_from_slice cannot fail");

    // Random 96-bit nonce from the OS; unique per encryption operation.
    // Reusing nonces with the same key would break GCM confidentiality.
    let nonce = Aes256Gcm::generate_nonce(&mut OsRng);

    // encrypt() returns ciphertext || tag (the last 16 bytes are the auth tag).
    // Cannot fail with valid nonce and key.
    let ciphertext = cipher
        .encrypt(&nonce, plaintext.as_bytes())
        .expect("AES-256-GCM encrypt: valid parameters, should not fail");

    // Layout: nonce[12] || ciphertext_with_tag
    let mut blob = Vec::with_capacity(12 + ciphertext.len());
    blob.extend_from_slice(nonce.as_slice());
    blob.extend_from_slice(&ciphertext);

    format!("{TOKEN_PREFIX}{}", STANDARD.encode(&blob))
}

/// Decrypts a token stored in the database.
///
/// | Stored value             | Behavior                                          |
/// |--------------------------|---------------------------------------------------|
/// | `v1:<b64>` + key OK      | Decrypts AES-256-GCM, returns plaintext            |
/// | `v1:<b64>` + no key      | `AppError::Internal` — config inconsistency       |
/// | No `v1:` prefix          | Direct return (legacy plaintext — Django compat)   |
///
/// The "no prefix" case allows reading existing Django rows without prior
/// migration, enabling incremental deployment of encryption.
pub fn decrypt_token(stored: &str) -> Result<String, AppError> {
    // ── Backward compatibility: token without prefix = legacy plaintext ──
    let Some(b64_part) = stored.strip_prefix(TOKEN_PREFIX) else {
        return Ok(stored.to_owned());
    };

    // Token with v1: prefix — requires key to decrypt
    let key_bytes = load_key().ok_or_else(|| {
        AppError::Internal(anyhow::anyhow!(
            "Encrypted token (`v1:`) found in DB but TOKEN_ENCRYPTION_KEY is not \
             configured. Configure the variable to be able to decrypt the token."
        ))
    })?;

    let blob = STANDARD.decode(b64_part).map_err(|e| {
        AppError::Internal(anyhow::anyhow!("token_cipher: invalid base64: {e}"))
    })?;

    // Minimum: nonce(12) + tag(16) = 28 bytes; ciphertext can be 0 bytes
    if blob.len() < 28 {
        return Err(AppError::Internal(anyhow::anyhow!(
            "token_cipher: blob too short ({} bytes, minimum 28)",
            blob.len()
        )));
    }

    let (nonce_bytes, ciphertext_with_tag) = blob.split_at(12);

    let cipher = Aes256Gcm::new_from_slice(&key_bytes)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("token_cipher: init cipher: {e}")))?;

    let nonce = Nonce::from_slice(nonce_bytes);

    // Automatically verifies auth tag; fails if key or data are incorrect.
    let plaintext_bytes = cipher
        .decrypt(nonce, ciphertext_with_tag)
        .map_err(|_| {
            AppError::Internal(anyhow::anyhow!(
                "token_cipher: decryption failed — incorrect key or corrupt data"
            ))
        })?;

    String::from_utf8(plaintext_bytes).map_err(|e| {
        AppError::Internal(anyhow::anyhow!("token_cipher: invalid UTF-8: {e}"))
    })
}

#[cfg(test)]
mod tests {
    use super::{decrypt_token, encrypt_token, TOKEN_PREFIX};
    use base64::Engine as _;
    use serial_test::serial;

    // ── Tests that do not require a configured key ───────────────────────────

    #[test]
    fn legacy_plaintext_passthrough() {
        // Token without v1: prefix → direct return (existing Django rows)
        let legacy = "ghs_plaintexttoken1234";
        assert_eq!(decrypt_token(legacy).unwrap(), legacy);
    }

    #[test]
    #[serial(token_cipher_env)]
    fn encrypt_without_key_returns_plaintext_with_warning() {
        // Without TOKEN_ENCRYPTION_KEY the value is stored unencrypted
        std::env::remove_var("TOKEN_ENCRYPTION_KEY");
        let token = "raw_token_value";
        let stored = encrypt_token(token);
        assert_eq!(stored, token);
        assert!(!stored.starts_with(TOKEN_PREFIX));
    }

    // ── Tests that require a key ─────────────────────────────────────────────

    fn set_test_key() {
        // 32 bytes of zeros encoded in base64 — ONLY for tests
        let key = base64::engine::general_purpose::STANDARD.encode([0u8; 32]);
        std::env::set_var("TOKEN_ENCRYPTION_KEY", key);
    }

    #[test]
    #[serial(token_cipher_env)]
    fn roundtrip_encrypt_decrypt() {
        set_test_key();
        let original = "ghs_realGitHubToken_abc123";
        let stored = encrypt_token(original);

        // The stored value is opaque and has the correct prefix
        assert!(stored.starts_with(TOKEN_PREFIX));
        assert_ne!(stored, original);

        // The decryption recovers the exact original
        let recovered = decrypt_token(&stored).unwrap();
        assert_eq!(recovered, original);
    }

    #[test]
    #[serial(token_cipher_env)]
    fn nonces_are_unique_per_call() {
        set_test_key();
        let token = "same_token";
        let a = encrypt_token(token);
        let b = encrypt_token(token);
        // Two encryptions of the same plaintext must be different (random nonce)
        assert_ne!(a, b, "nonces must be unique per call");
    }

    #[test]
    #[serial(token_cipher_env)]
    fn tampered_ciphertext_fails_auth() {
        set_test_key();
        let stored = encrypt_token("legit_token");

        // Extract the binary blob (nonce + ciphertext) from v1:<b64>
        let b64_part = stored.strip_prefix(TOKEN_PREFIX).unwrap();
        let mut blob = base64::engine::general_purpose::STANDARD
            .decode(b64_part)
            .unwrap();

        // Corrupt the last byte of the ciphertext (outside the 12-byte nonce).
        // This invalidates the GCM auth tag without producing non-UTF-8 bytes in the string.
        *blob.last_mut().unwrap() ^= 0xFF;

        // Re-encode as v1:<b64> — the resulting string is valid UTF-8
        let tampered = format!(
            "{TOKEN_PREFIX}{}",
            base64::engine::general_purpose::STANDARD.encode(&blob)
        );

        assert!(
            decrypt_token(&tampered).is_err(),
            "GCM auth tag must detect tampering"
        );
    }
}
