use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20240101_000001_auth_django"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // django_content_type
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_content_type"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("app_label"))
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("model"))
                            .string_len(100)
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("django_content_type_app_label_model_76bd3d3b_uniq")
                    .table(Alias::new("django_content_type"))
                    .col(Alias::new("app_label"))
                    .col(Alias::new("model"))
                    .to_owned(),
            )
            .await?;

        // auth_group
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("auth_group"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("name"))
                            .string_len(150)
                            .not_null()
                            .unique_key(),
                    )
                    .to_owned(),
            )
            .await?;

        // auth_permission
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("auth_permission"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("content_type_id"))
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("codename"))
                            .string_len(100)
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("auth_permission_content_type_id_2f476e4b_fk_django_co")
                            .from(Alias::new("auth_permission"), Alias::new("content_type_id"))
                            .to(Alias::new("django_content_type"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("auth_permission_content_type_id_codename_01ab375a_uniq")
                    .table(Alias::new("auth_permission"))
                    .col(Alias::new("content_type_id"))
                    .col(Alias::new("codename"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("auth_permission_content_type_id_2f476e4b")
                    .table(Alias::new("auth_permission"))
                    .col(Alias::new("content_type_id"))
                    .to_owned(),
            )
            .await?;

        // auth_group_permissions
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("auth_group_permissions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("group_id")).integer().not_null())
                    .col(
                        ColumnDef::new(Alias::new("permission_id"))
                            .integer()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("auth_group_permissions_group_id_b120cbf9_fk_auth_group_id")
                            .from(Alias::new("auth_group_permissions"), Alias::new("group_id"))
                            .to(Alias::new("auth_group"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("auth_group_permissio_permission_id_84c5c92e_fk_auth_perm")
                            .from(
                                Alias::new("auth_group_permissions"),
                                Alias::new("permission_id"),
                            )
                            .to(Alias::new("auth_permission"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("auth_group_permissions_group_id_permission_id_0cd325b0_uniq")
                    .table(Alias::new("auth_group_permissions"))
                    .col(Alias::new("group_id"))
                    .col(Alias::new("permission_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("auth_group_permissions_group_id_b120cbf9")
                    .table(Alias::new("auth_group_permissions"))
                    .col(Alias::new("group_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("auth_group_permissions_permission_id_84c5c92e")
                    .table(Alias::new("auth_group_permissions"))
                    .col(Alias::new("permission_id"))
                    .to_owned(),
            )
            .await?;

        // django_migrations
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_migrations"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("app")).string_len(255).not_null())
                    .col(
                        ColumnDef::new(Alias::new("name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("applied"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // django_session
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_session"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("session_key"))
                            .string_len(40)
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("session_data")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("expire_date"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("django_session_expire_date_a5c62663")
                    .table(Alias::new("django_session"))
                    .col(Alias::new("expire_date"))
                    .to_owned(),
            )
            .await?;

        // django_celery_beat tables
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_clockedschedule"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("clocked_time"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_crontabschedule"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("minute"))
                            .string_len(240)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("hour")).string_len(96).not_null())
                    .col(
                        ColumnDef::new(Alias::new("day_of_week"))
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("day_of_month"))
                            .string_len(124)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("month_of_year"))
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("timezone"))
                            .string_len(63)
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_intervalschedule"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("every")).integer().not_null())
                    .col(
                        ColumnDef::new(Alias::new("period"))
                            .string_len(24)
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_solarschedule"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("event"))
                            .string_len(24)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("latitude"))
                            .decimal_len(9, 6)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("longitude"))
                            .decimal_len(9, 6)
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq")
                    .table(Alias::new("django_celery_beat_solarschedule"))
                    .col(Alias::new("event"))
                    .col(Alias::new("latitude"))
                    .col(Alias::new("longitude"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_periodictask"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("name"))
                            .string_len(200)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("task"))
                            .string_len(200)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("args")).text().not_null())
                    .col(ColumnDef::new(Alias::new("kwargs")).text().not_null())
                    .col(ColumnDef::new(Alias::new("queue")).string_len(200).null())
                    .col(
                        ColumnDef::new(Alias::new("exchange"))
                            .string_len(200)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("routing_key"))
                            .string_len(200)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("expires"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("enabled")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("last_run_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("total_run_count"))
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("date_changed"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("description")).text().not_null())
                    .col(ColumnDef::new(Alias::new("crontab_id")).integer().null())
                    .col(ColumnDef::new(Alias::new("interval_id")).integer().null())
                    .col(ColumnDef::new(Alias::new("solar_id")).integer().null())
                    .col(ColumnDef::new(Alias::new("one_off")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("start_time"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("priority")).integer().null())
                    .col(ColumnDef::new(Alias::new("headers")).text().not_null())
                    .col(ColumnDef::new(Alias::new("clocked_id")).integer().null())
                    .col(
                        ColumnDef::new(Alias::new("expire_seconds"))
                            .integer()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("django_celery_beat_p_clocked_id_47a69f82_fk_django_ce")
                            .from(
                                Alias::new("django_celery_beat_periodictask"),
                                Alias::new("clocked_id"),
                            )
                            .to(
                                Alias::new("django_celery_beat_clockedschedule"),
                                Alias::new("id"),
                            )
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("django_celery_beat_p_crontab_id_d3cba168_fk_django_ce")
                            .from(
                                Alias::new("django_celery_beat_periodictask"),
                                Alias::new("crontab_id"),
                            )
                            .to(
                                Alias::new("django_celery_beat_crontabschedule"),
                                Alias::new("id"),
                            )
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("django_celery_beat_p_interval_id_a8ca27da_fk_django_ce")
                            .from(
                                Alias::new("django_celery_beat_periodictask"),
                                Alias::new("interval_id"),
                            )
                            .to(
                                Alias::new("django_celery_beat_intervalschedule"),
                                Alias::new("id"),
                            )
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("django_celery_beat_p_solar_id_a87ce72c_fk_django_ce")
                            .from(
                                Alias::new("django_celery_beat_periodictask"),
                                Alias::new("solar_id"),
                            )
                            .to(
                                Alias::new("django_celery_beat_solarschedule"),
                                Alias::new("id"),
                            )
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("django_celery_beat_periodictask_crontab_id_d3cba168")
                    .table(Alias::new("django_celery_beat_periodictask"))
                    .col(Alias::new("crontab_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("django_celery_beat_periodictask_interval_id_a8ca27da")
                    .table(Alias::new("django_celery_beat_periodictask"))
                    .col(Alias::new("interval_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("django_celery_beat_periodictask_solar_id_a87ce72c")
                    .table(Alias::new("django_celery_beat_periodictask"))
                    .col(Alias::new("solar_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("django_celery_beat_periodictask_clocked_id_47a69f82")
                    .table(Alias::new("django_celery_beat_periodictask"))
                    .col(Alias::new("clocked_id"))
                    .to_owned(),
            )
            .await?;

        // django_celery_beat_periodictasks (singular sentinel table)
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("django_celery_beat_periodictasks"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("ident"))
                            .small_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_update"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // instances (no user FK yet - users doesn't exist)
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("instances"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("instance_name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("whitelist_emails")).text().null())
                    .col(
                        ColumnDef::new(Alias::new("instance_id"))
                            .string_len(255)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("current_version"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_checked_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("namespace"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_telemetry_enabled"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_support_required"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_setup_done"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_signup_screen_visited"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_verified"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("domain")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("latest_version"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("edition"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("is_test")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("is_current_version_deprecated"))
                            .boolean()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // integrations
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("integrations"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("title"))
                            .string_len(400)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("provider"))
                            .string_len(400)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Alias::new("network")).integer().not_null())
                    .col(
                        ColumnDef::new(Alias::new("description"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("author"))
                            .string_len(400)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("webhook_url")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("webhook_secret"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("redirect_url")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("metadata"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("verified")).boolean().not_null())
                    .col(ColumnDef::new(Alias::new("avatar_url")).text().null())
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // changelogs (no user FK yet)
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("changelogs"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("title"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("description")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("version"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("tags")).json_binary().not_null())
                    .col(
                        ColumnDef::new(Alias::new("release_date"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_release_candidate"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in [
            "changelogs",
            "integrations",
            "instances",
            "django_celery_beat_periodictasks",
            "django_celery_beat_periodictask",
            "django_celery_beat_solarschedule",
            "django_celery_beat_intervalschedule",
            "django_celery_beat_crontabschedule",
            "django_celery_beat_clockedschedule",
            "django_session",
            "django_migrations",
            "auth_group_permissions",
            "auth_permission",
            "auth_group",
            "django_content_type",
        ] {
            manager
                .drop_table(
                    Table::drop()
                        .table(Alias::new(table))
                        .if_exists()
                        .cascade()
                        .to_owned(),
                )
                .await?;
        }
        Ok(())
    }
}
