use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20240101_000002_users_and_sessions"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // sessions (no user FK - plain session store)
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("sessions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("session_key"))
                            .string_len(128)
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("session_data")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("expire_date"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("device_info"))
                            .json_binary()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).string_len(50).null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("sessions_expire_date_16e4c444")
                    .table(Alias::new("sessions"))
                    .col(Alias::new("expire_date"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("sessions_user_id_05e26f4a")
                    .table(Alias::new("sessions"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        // file_assets - created before users because of circular FK
        // users.avatar_asset_id -> file_assets.id
        // file_assets.created_by_id -> users.id
        // We create file_assets first WITHOUT the user FKs, add them later
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("file_assets"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("attributes"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("asset"))
                            .string_len(800)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("workspace_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("is_deleted"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_archived"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("comment_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("entity_type"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("external_id"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("external_source"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_uploaded"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("issue_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("page_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("project_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("size")).double().not_null())
                    .col(
                        ColumnDef::new(Alias::new("storage_metadata"))
                            .json_binary()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("draft_issue_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("entity_identifier"))
                            .string_len(255)
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("asset_asset_idx")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("asset"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("asset_entity_type_idx")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("entity_type"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("asset_entity_identifier_idx")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("entity_identifier"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("asset_entity_idx")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("entity_type"))
                    .col(Alias::new("entity_identifier"))
                    .to_owned(),
            )
            .await?;

        // users - created after file_assets so avatar_asset_id FK can point to it
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("users"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("password"))
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("username"))
                            .string_len(128)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("mobile_number"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("email"))
                            .string_len(255)
                            .null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("first_name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("avatar")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("date_joined"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_location"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_location"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_superuser"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_managed"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_password_expired"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("is_active")).boolean().not_null())
                    .col(ColumnDef::new(Alias::new("is_staff")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("is_email_verified"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_password_autoset"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("token"))
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("user_timezone"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_active"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login_time"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_logout_time"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login_ip"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_logout_ip"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login_medium"))
                            .string_len(20)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login_uagent"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("token_updated_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("is_bot")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("cover_image"))
                            .string_len(800)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("display_name"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("avatar_asset_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("cover_image_asset_id"))
                            .uuid()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("bot_type")).string_len(30).null())
                    .col(
                        ColumnDef::new(Alias::new("is_email_valid"))
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("masked_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("is_password_reset_required"))
                            .boolean()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("users_avatar_asset_id_50fa2043_fk_file_assets_id")
                            .from(Alias::new("users"), Alias::new("avatar_asset_id"))
                            .to(Alias::new("file_assets"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("users_cover_image_asset_id_b9679cbc_fk_file_assets_id")
                            .from(Alias::new("users"), Alias::new("cover_image_asset_id"))
                            .to(Alias::new("file_assets"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("users_avatar_asset_id_50fa2043")
                    .table(Alias::new("users"))
                    .col(Alias::new("avatar_asset_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("users_cover_image_asset_id_b9679cbc")
                    .table(Alias::new("users"))
                    .col(Alias::new("cover_image_asset_id"))
                    .to_owned(),
            )
            .await?;

        // Now add file_assets -> users FKs
        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("file_asset_created_by_id_966942a0_fk_user_id")
                    .from(Alias::new("file_assets"), Alias::new("created_by_id"))
                    .to(Alias::new("users"), Alias::new("id"))
                    .on_delete(ForeignKeyAction::NoAction)
                    .on_update(ForeignKeyAction::NoAction)
                    .to_owned(),
            )
            .await?;

        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("file_asset_updated_by_id_d6aaf4f0_fk_user_id")
                    .from(Alias::new("file_assets"), Alias::new("updated_by_id"))
                    .to(Alias::new("users"), Alias::new("id"))
                    .on_delete(ForeignKeyAction::NoAction)
                    .on_update(ForeignKeyAction::NoAction)
                    .to_owned(),
            )
            .await?;

        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("file_assets_user_id_ce1818dc_fk_users_id")
                    .from(Alias::new("file_assets"), Alias::new("user_id"))
                    .to(Alias::new("users"), Alias::new("id"))
                    .on_delete(ForeignKeyAction::NoAction)
                    .on_update(ForeignKeyAction::NoAction)
                    .to_owned(),
            )
            .await?;

        // Index for file_assets user refs
        manager
            .create_index(
                Index::create()
                    .name("file_asset_created_by_id_966942a0")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("created_by_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("file_asset_updated_by_id_d6aaf4f0")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("updated_by_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("file_assets_user_id_ce1818dc")
                    .table(Alias::new("file_assets"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        // users_groups
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("users_groups"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("group_id")).integer().not_null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_groups_user_id_abaea130_fk_user_id")
                            .from(Alias::new("users_groups"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_groups_group_id_b76f8aba_fk_auth_group_id")
                            .from(Alias::new("users_groups"), Alias::new("group_id"))
                            .to(Alias::new("auth_group"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("user_groups_user_id_group_id_40beef00_uniq")
                    .table(Alias::new("users_groups"))
                    .col(Alias::new("user_id"))
                    .col(Alias::new("group_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("user_groups_user_id_abaea130")
                    .table(Alias::new("users_groups"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("user_groups_group_id_b76f8aba")
                    .table(Alias::new("users_groups"))
                    .col(Alias::new("group_id"))
                    .to_owned(),
            )
            .await?;

        // users_user_permissions
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("users_user_permissions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("permission_id"))
                            .integer()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_user_permissions_user_id_ed4a47ea_fk_user_id")
                            .from(Alias::new("users_user_permissions"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_user_permission_permission_id_9deb68a3_fk_auth_perm")
                            .from(
                                Alias::new("users_user_permissions"),
                                Alias::new("permission_id"),
                            )
                            .to(Alias::new("auth_permission"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("user_user_permissions_user_id_permission_id_7dc6e2e0_uniq")
                    .table(Alias::new("users_user_permissions"))
                    .col(Alias::new("user_id"))
                    .col(Alias::new("permission_id"))
                    .to_owned(),
            )
            .await?;

        // social_login_connections
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("social_login_connections"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("medium"))
                            .string_len(20)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_login_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_received_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("token_data"))
                            .json_binary()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("extra_data"))
                            .json_binary()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("social_login_connection_created_by_id_7ca2ef50_fk_user_id")
                            .from(
                                Alias::new("social_login_connections"),
                                Alias::new("created_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("social_login_connection_updated_by_id_c13deb42_fk_user_id")
                            .from(
                                Alias::new("social_login_connections"),
                                Alias::new("updated_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("social_login_connection_user_id_0e26c0c5_fk_user_id")
                            .from(
                                Alias::new("social_login_connections"),
                                Alias::new("user_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        // accounts
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("accounts"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("provider_account_id"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("provider")).string().not_null())
                    .col(ColumnDef::new(Alias::new("access_token")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("access_token_expired_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("refresh_token")).text().null())
                    .col(
                        ColumnDef::new(Alias::new("refresh_token_expired_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("last_connected_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("metadata"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("id_token")).text().not_null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("accounts_user_id_7f1e1f1e_fk_users_id")
                            .from(Alias::new("accounts"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("accounts_provider_provider_account_id_daac1f10_uniq")
                    .table(Alias::new("accounts"))
                    .col(Alias::new("provider"))
                    .col(Alias::new("provider_account_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("accounts_user_id_7f1e1f1e")
                    .table(Alias::new("accounts"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        // devices
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("devices"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("device_id"))
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("device_type"))
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("push_token"))
                            .string_len(255)
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("is_active")).boolean().not_null())
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("devices_created_by_id_410a755b_fk_users_id")
                            .from(Alias::new("devices"), Alias::new("created_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("devices_updated_by_id_ee20dc3c_fk_users_id")
                            .from(Alias::new("devices"), Alias::new("updated_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("devices_user_id_9a5cca49_fk_users_id")
                            .from(Alias::new("devices"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("devices_user_id_9a5cca49")
                    .table(Alias::new("devices"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        // device_sessions
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("device_sessions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("is_active")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("user_agent"))
                            .string_len(255)
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("ip_address")).string().null())
                    .col(
                        ColumnDef::new(Alias::new("start_time"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("end_time"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("device_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("session_id"))
                            .string_len(128)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("device_sessions_created_by_id_920a3bd5_fk_users_id")
                            .from(Alias::new("device_sessions"), Alias::new("created_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("device_sessions_updated_by_id_d0bd0c76_fk_users_id")
                            .from(Alias::new("device_sessions"), Alias::new("updated_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("device_sessions_device_id_a42b2ada_fk_devices_id")
                            .from(Alias::new("device_sessions"), Alias::new("device_id"))
                            .to(Alias::new("devices"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("device_sessions_session_id_5382b02b_fk_sessions_session_key")
                            .from(Alias::new("device_sessions"), Alias::new("session_id"))
                            .to(Alias::new("sessions"), Alias::new("session_key"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("device_sessions_device_id_a42b2ada")
                    .table(Alias::new("device_sessions"))
                    .col(Alias::new("device_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("device_sessions_session_id_5382b02b")
                    .table(Alias::new("device_sessions"))
                    .col(Alias::new("session_id"))
                    .to_owned(),
            )
            .await?;

        // user_github_connections
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("user_github_connections"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("github_user_id"))
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("github_username"))
                            .string_len(150)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("github_avatar_url"))
                            .string_len(200)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("access_token")).text().not_null())
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("user_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_github_connections_created_by_id_99678dc5_fk_users_id")
                            .from(
                                Alias::new("user_github_connections"),
                                Alias::new("created_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_github_connections_updated_by_id_de42cb21_fk_users_id")
                            .from(
                                Alias::new("user_github_connections"),
                                Alias::new("updated_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("user_github_connections_user_id_f0a0dd79_fk_users_id")
                            .from(Alias::new("user_github_connections"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        // instance_configurations and instance_admins
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("instance_configurations"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("key"))
                            .string_len(100)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Alias::new("value")).text().null())
                    .col(ColumnDef::new(Alias::new("category")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("is_encrypted"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_configurations_created_by_id_e683f3e5_fk_users_id")
                            .from(
                                Alias::new("instance_configurations"),
                                Alias::new("created_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_configurations_updated_by_id_f0d7542e_fk_users_id")
                            .from(
                                Alias::new("instance_configurations"),
                                Alias::new("updated_by_id"),
                            )
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Alias::new("instance_admins"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("role")).integer().not_null())
                    .col(
                        ColumnDef::new(Alias::new("is_verified"))
                            .boolean()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("created_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("instance_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("updated_by_id")).uuid().null())
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("deleted_at"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_admins_created_by_id_7f4e03b4_fk_users_id")
                            .from(Alias::new("instance_admins"), Alias::new("created_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_admins_updated_by_id_b7800403_fk_users_id")
                            .from(Alias::new("instance_admins"), Alias::new("updated_by_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_admins_user_id_cc6e9b62_fk_users_id")
                            .from(Alias::new("instance_admins"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("instance_admins_instance_id_66d1ba73_fk_instances_id")
                            .from(Alias::new("instance_admins"), Alias::new("instance_id"))
                            .to(Alias::new("instances"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::NoAction)
                            .on_update(ForeignKeyAction::NoAction),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .unique()
                    .name("instance_admins_instance_id_user_id_2e80a466_uniq")
                    .table(Alias::new("instance_admins"))
                    .col(Alias::new("instance_id"))
                    .col(Alias::new("user_id"))
                    .to_owned(),
            )
            .await?;

        // Add user FKs to instances now that users table exists
        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("instances_created_by_id_c76e92ef_fk_users_id")
                    .from(Alias::new("instances"), Alias::new("created_by_id"))
                    .to(Alias::new("users"), Alias::new("id"))
                    .on_delete(ForeignKeyAction::NoAction)
                    .on_update(ForeignKeyAction::NoAction)
                    .to_owned(),
            )
            .await?;

        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("instances_updated_by_id_cce8fcdf_fk_users_id")
                    .from(Alias::new("instances"), Alias::new("updated_by_id"))
                    .to(Alias::new("users"), Alias::new("id"))
                    .on_delete(ForeignKeyAction::NoAction)
                    .on_update(ForeignKeyAction::NoAction)
                    .to_owned(),
            )
            .await?;

        // Add user FKs to integrations and changelogs
        for (fk_name, table, col) in [
            (
                "integrations_created_by_id_0b6edd52_fk_users_id",
                "integrations",
                "created_by_id",
            ),
            (
                "integrations_updated_by_id_d6d00d15_fk_users_id",
                "integrations",
                "updated_by_id",
            ),
            (
                "changelogs_created_by_id_16dd944a_fk_users_id",
                "changelogs",
                "created_by_id",
            ),
            (
                "changelogs_updated_by_id_e0989861_fk_users_id",
                "changelogs",
                "updated_by_id",
            ),
        ] {
            manager
                .create_foreign_key(
                    ForeignKey::create()
                        .name(fk_name)
                        .from(Alias::new(table), Alias::new(col))
                        .to(Alias::new("users"), Alias::new("id"))
                        .on_delete(ForeignKeyAction::NoAction)
                        .on_update(ForeignKeyAction::NoAction)
                        .to_owned(),
                )
                .await?;
        }

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in [
            "instance_admins",
            "instance_configurations",
            "user_github_connections",
            "device_sessions",
            "devices",
            "accounts",
            "social_login_connections",
            "users_user_permissions",
            "users_groups",
            "users",
            "file_assets",
            "sessions",
        ] {
            manager
                .drop_table(
                    Table::drop()
                        .table(Alias::new(table))
                        .if_exists()
                        .cascade()
                        .to_owned(),
                )
                .await?;
        }
        Ok(())
    }
}
