// src/routes/timezones.rs
//! Endpoint de timezones — equivalente a `plane/app/views/timezone/base.py`.
//!
//! Devuelve la lista estática de zonas horarias soportadas por Plane.
//! No requiere autenticación.
//!
//! Ruta: GET /api/timezones/

use axum::{response::IntoResponse, Json};

/// Lista completa de timezones soportadas por Plane.
/// Equivalente al enum `TIMEZONE` en Django `settings.py`.
const TIMEZONES: &[&str] = &[
    "Pacific/Midway",
    "Pacific/Honolulu",
    "America/Juneau",
    "America/Boise",
    "America/Dawson",
    "America/Chihuahua",
    "America/Phoenix",
    "America/Chicago",
    "America/Regina",
    "America/Mexico_City",
    "America/Belize",
    "America/Detroit",
    "America/Indiana/Indianapolis",
    "America/Indiana/Starke",
    "America/Kentucky/Louisville",
    "America/New_York",
    "America/Toronto",
    "America/Caracas",
    "America/Halifax",
    "America/Thule",
    "America/Glace_Bay",
    "America/St_Johns",
    "America/Buenos_Aires",
    "America/Sao_Paulo",
    "America/Araguaina",
    "America/Godthab",
    "Atlantic/South_Georgia",
    "Atlantic/Azores",
    "Atlantic/Cape_Verde",
    "Africa/Casablanca",
    "Europe/Dublin",
    "Europe/Lisbon",
    "Europe/London",
    "Africa/Monrovia",
    "Europe/Amsterdam",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Budapest",
    "Europe/Copenhagen",
    "Europe/Ljubljana",
    "Europe/Madrid",
    "Europe/Paris",
    "Europe/Prague",
    "Europe/Rome",
    "Europe/Sarajevo",
    "Europe/Skopje",
    "Europe/Stockholm",
    "Europe/Vienna",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Africa/Lagos",
    "Africa/Bangui",
    "Africa/Windhoek",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Europe/Athens",
    "Europe/Bucharest",
    "Asia/Cairo",
    "Africa/Nairobi",
    "Europe/Helsinki",
    "Europe/Istanbul",
    "Asia/Jerusalem",
    "Asia/Baghdad",
    "Europe/Kaliningrad",
    "Asia/Kuwait",
    "Asia/Riyadh",
    "Africa/Djibouti",
    "Asia/Tehran",
    "Asia/Muscat",
    "Asia/Baku",
    "Asia/Tbilisi",
    "Asia/Yerevan",
    "Asia/Kabul",
    "Asia/Yekaterinburg",
    "Asia/Tashkent",
    "Asia/Almaty",
    "Asia/Kolkata",
    "Asia/Katmandu",
    "Asia/Dhaka",
    "Asia/Colombo",
    "Asia/Rangoon",
    "Asia/Bangkok",
    "Asia/Jakarta",
    "Asia/Novosibirsk",
    "Asia/Krasnoyarsk",
    "Asia/Hong_Kong",
    "Asia/Kuala_Lumpur",
    "Asia/Manila",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Taipei",
    "Asia/Urumqi",
    "Australia/Perth",
    "Asia/Irkutsk",
    "Asia/Ulaanbaatar",
    "Asia/Seoul",
    "Asia/Tokyo",
    "Asia/Yakutsk",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Australia/Brisbane",
    "Australia/Canberra",
    "Australia/Hobart",
    "Australia/Melbourne",
    "Australia/Sydney",
    "Pacific/Guam",
    "Pacific/Port_Moresby",
    "Asia/Vladivostok",
    "Asia/Magadan",
    "Pacific/Auckland",
    "Pacific/Fiji",
    "UTC",
];

/// GET /api/timezones/
///
/// Retorna la lista de zonas horarias soportadas.
/// No requiere autenticación.
#[utoipa::path(
    get,
    path = "/timezones/",
    tag = "Timezones",
    responses(
        (status = 200, description = "List of supported timezones"),
    )
)]
pub async fn list_timezones() -> impl IntoResponse {
    Json(TIMEZONES)
}
